"""The ``Finding`` record and report rendering (JSON + Markdown).

Findings are app-agnostic: the report header is filled from the discovered
``AppProfile`` so the same renderer serves any target.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field

from .taxonomy import OWASP_2021, SEVERITIES

_SEV_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4, "SAFE": 5}
_SEV_BADGE = {
    "CRITICAL": "🟥 CRITICAL", "HIGH": "🟧 HIGH", "MEDIUM": "🟨 MEDIUM",
    "LOW": "🟦 LOW", "INFO": "⬜ INFO", "SAFE": "🟩 TESTED-SAFE",
}


@dataclass
class Finding:
    id: str                          # stable slug, e.g. "a01-users-unauth-list"
    owasp: str                       # "A01".."A10"
    title: str
    severity: str                    # one of SEVERITIES
    summary: str                     # one-paragraph what/impact
    evidence: str = ""               # request/response excerpts, PoC output
    reproduction: str = ""           # exact steps / command to reproduce
    references: list[str] = field(default_factory=list)
    tools: list[str] = field(default_factory=list)   # public tools for this class
    module: str = ""                 # which module produced it (filled by runner)

    def __post_init__(self) -> None:
        if self.severity not in SEVERITIES:
            raise ValueError(f"bad severity: {self.severity}")
        if self.owasp not in OWASP_2021:
            raise ValueError(f"bad owasp id: {self.owasp}")


def write_reports(findings: list[Finding], out_dir: str, meta: dict) -> tuple[str, str]:
    os.makedirs(out_dir, exist_ok=True)
    json_path = os.path.join(out_dir, "findings.json")
    with open(json_path, "w") as fh:
        json.dump({"meta": meta, "findings": [asdict(f) for f in findings]}, fh, indent=2)
    md_path = os.path.join(out_dir, "REPORT.md")
    with open(md_path, "w") as fh:
        fh.write(_render_md(findings, meta))
    return json_path, md_path


def _render_md(findings: list[Finding], meta: dict) -> str:
    real = [f for f in findings if f.severity != "SAFE"]
    safe = [f for f in findings if f.severity == "SAFE"]
    counts = {s: sum(1 for f in real if f.severity == s) for s in SEVERITIES if s != "SAFE"}
    app = meta.get("app_name", "target")

    L: list[str] = []
    L.append(f"# {app} — Web Application Penetration Test\n")
    L.append(f"- **Target:** {meta.get('base_url')}")
    L.append(f"- **Date:** {meta.get('date')}")
    L.append(f"- **Framework:** {meta.get('framework', 'FastAPI (auto-detected)')}")
    L.append(f"- **Mode:** {'SAFE (non-destructive)' if meta.get('safe') else 'FULL (active exploitation)'}")
    L.append(f"- **Routes discovered:** {meta.get('route_count', '?')}")
    L.append(f"- **Principals bootstrapped:** {', '.join(meta.get('principals', [])) or 'none'}")
    L.append("")
    L.append("> Automated assessment generated by **Heimdall**. Run only against systems "
             "you own or are explicitly authorized to test.\n")

    L.append("## Executive summary\n")
    L.append("| Severity | Count |")
    L.append("|---|---|")
    for s in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        L.append(f"| {_SEV_BADGE[s]} | {counts.get(s, 0)} |")
    L.append(f"| {_SEV_BADGE['SAFE']} | {len(safe)} |")
    L.append("")

    from .chains import build_chains
    chains = build_chains(findings)
    if chains:
        L.append("## Attack chains\n")
        L.append("How the findings compose into end-to-end attacks (highest-impact first):\n")
        for i, c in enumerate(chains, 1):
            L.append(f"### ⛓️ {i}. [{c.severity}] {c.title}\n")
            for step in c.steps:
                L.append(f"1. {step}")
            L.append("")
            if c.finding_ids:
                L.append(f"*Chained findings: {', '.join('`' + fid + '`' for fid in c.finding_ids)}*\n")
        L.append("---\n")

    L.append("### Findings at a glance\n")
    L.append("| # | Severity | OWASP | Finding |")
    L.append("|---|---|---|---|")
    ordered = sorted(findings, key=lambda f: (_SEV_ORDER[f.severity], f.owasp))
    for i, f in enumerate(ordered, 1):
        L.append(f"| {i} | {_SEV_BADGE[f.severity]} | {f.owasp} | {f.title} |")
    L.append("")

    L.append("---\n")
    L.append("## Detailed findings\n")
    for i, f in enumerate(ordered, 1):
        L.append(f"### {i}. [{f.severity}] {f.title}")
        L.append(f"- **OWASP:** {OWASP_2021[f.owasp]}")
        L.append(f"- **ID:** `{f.id}`" + (f" · **module:** `{f.module}`" if f.module else "") + "\n")
        L.append(f"{f.summary}\n")
        if f.evidence:
            L.append("**Evidence / PoC output:**\n")
            L.append("```\n" + f.evidence.strip() + "\n```\n")
        if f.reproduction:
            L.append("**Reproduction:**\n")
            L.append(f.reproduction.strip() + "\n")
        if f.references:
            L.append("**References:** " + " · ".join(f.references) + "\n")
        if f.tools:
            L.append("**Tools:** " + ", ".join(f.tools) + "\n")
        L.append("---\n")

    if meta.get("notes"):
        L.append("## Run notes\n")
        for n in meta["notes"]:
            L.append(f"- {n}")
        L.append("")
    return "\n".join(L)
