"""The ``Finding`` record and report rendering (JSON + Markdown).

Findings are app-agnostic: the report header is filled from the discovered
``AppProfile`` so the same renderer serves any target.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field

from .taxonomy import CVSS_BAND, OWASP_2021, SEVERITIES

_SEV_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4, "SAFE": 5}
_SEV_BADGE = {
    "CRITICAL": "🟥 CRITICAL", "HIGH": "🟧 HIGH", "MEDIUM": "🟨 MEDIUM",
    "LOW": "🟦 LOW", "INFO": "⬜ INFO", "SAFE": "🟩 TESTED-SAFE",
}


@dataclass
class Finding:
    id: str                          # stable slug, e.g. "a01-users-unauth-list"
    owasp: str                       # "A01".."A10"
    title: str
    severity: str                    # one of SEVERITIES
    summary: str                     # one-paragraph what/impact
    evidence: str = ""               # request/response excerpts, PoC output
    reproduction: str = ""           # exact steps / command to reproduce
    references: list[str] = field(default_factory=list)
    tools: list[str] = field(default_factory=list)   # public tools for this class
    module: str = ""                 # which module produced it (filled by runner)
    route: str = ""                  # affected endpoint, e.g. "POST /tickets/{id}/scan"
    request: str = ""                # concrete request that triggers it (curl / method+path+body)
    location: str = ""               # source file:line of the handler (filled if --source)

    def __post_init__(self) -> None:
        if self.severity not in SEVERITIES:
            raise ValueError(f"bad severity: {self.severity}")
        if self.owasp not in OWASP_2021:
            raise ValueError(f"bad owasp id: {self.owasp}")


def write_reports(findings: list[Finding], out_dir: str, meta: dict) -> tuple[str, str, str]:
    os.makedirs(out_dir, exist_ok=True)
    json_path = os.path.join(out_dir, "findings.json")
    with open(json_path, "w") as fh:
        json.dump({"meta": meta, "findings": [asdict(f) for f in findings]}, fh, indent=2)
    md_path = os.path.join(out_dir, "REPORT.md")
    with open(md_path, "w") as fh:
        fh.write(_render_md(findings, meta))
    html_path = os.path.join(out_dir, "REPORT.html")
    with open(html_path, "w") as fh:
        fh.write(_render_html(findings, meta))
    from .sarif import to_sarif
    sarif_path = os.path.join(out_dir, "findings.sarif")
    with open(sarif_path, "w") as fh:
        json.dump(to_sarif(findings, meta), fh, indent=2)
    return json_path, md_path, html_path, sarif_path


def _render_md(findings: list[Finding], meta: dict) -> str:
    real = [f for f in findings if f.severity != "SAFE"]
    safe = [f for f in findings if f.severity == "SAFE"]
    counts = {s: sum(1 for f in real if f.severity == s) for s in SEVERITIES if s != "SAFE"}
    app = meta.get("app_name", "target")

    L: list[str] = []
    L.append(f"# {app} — Web Application Penetration Test\n")
    L.append(f"- **Target:** {meta.get('base_url')}")
    L.append(f"- **Date:** {meta.get('date')}")
    L.append(f"- **Framework:** {meta.get('framework', 'FastAPI (auto-detected)')}")
    L.append(f"- **Mode:** {'SAFE (non-destructive)' if meta.get('safe') else 'FULL (active exploitation)'}")
    L.append(f"- **Routes discovered:** {meta.get('route_count', '?')}")
    L.append(f"- **Principals bootstrapped:** {', '.join(meta.get('principals', [])) or 'none'}")
    L.append("")
    L.append("> Automated assessment generated by **Heimdall**. Run only against systems "
             "you own or are explicitly authorized to test.\n")

    L.append("## Executive summary\n")
    L.append("| Severity | Count |")
    L.append("|---|---|")
    for s in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        L.append(f"| {_SEV_BADGE[s]} | {counts.get(s, 0)} |")
    L.append(f"| {_SEV_BADGE['SAFE']} | {len(safe)} |")
    L.append("")

    from .chains import build_chains
    chains = build_chains(findings)
    if chains:
        L.append("## Attack chains\n")
        L.append("How the findings compose into end-to-end attacks (highest-impact first):\n")
        for i, c in enumerate(chains, 1):
            L.append(f"### ⛓️ {i}. [{c.severity}] {c.title}\n")
            for step in c.steps:
                L.append(f"1. {step}")
            L.append("")
            if c.finding_ids:
                L.append(f"*Chained findings: {', '.join('`' + fid + '`' for fid in c.finding_ids)}*\n")
        L.append("---\n")

    L.append("### Findings at a glance\n")
    L.append("| # | Severity | CVSS* | OWASP | Finding |")
    L.append("|---|---|---|---|---|")
    ordered = sorted(findings, key=lambda f: (_SEV_ORDER[f.severity], f.owasp))
    for i, f in enumerate(ordered, 1):
        L.append(f"| {i} | {_SEV_BADGE[f.severity]} | {CVSS_BAND[f.severity]} | "
                 f"{f.owasp} | {f.title} |")
    L.append("\n<sub>*CVSS is an indicative severity-band score, not a per-finding "
             "computed vector.</sub>\n")

    L.append("---\n")
    L.append("## Detailed findings\n")
    for i, f in enumerate(ordered, 1):
        L.append(f"### {i}. [{f.severity}] {f.title}")
        L.append(f"- **OWASP:** {OWASP_2021[f.owasp]}")
        if f.severity != "SAFE":
            L.append(f"- **Severity:** {f.severity} (indicative CVSS {CVSS_BAND[f.severity]})")
        L.append(f"- **ID:** `{f.id}`" + (f" · **module:** `{f.module}`" if f.module else ""))
        if f.route:
            L.append(f"- **Route:** `{f.route}`")
        if f.location:
            L.append(f"- **Source:** `{f.location}`")
        L.append("")
        L.append(f"{f.summary}\n")
        if f.request:
            L.append("**Triggering request:**\n")
            L.append("```http\n" + f.request.strip() + "\n```\n")
        if f.evidence:
            L.append("**Evidence / PoC output:**\n")
            L.append("```\n" + f.evidence.strip() + "\n```\n")
        if f.reproduction:
            L.append("**Reproduction:**\n")
            L.append(f.reproduction.strip() + "\n")
        if f.references:
            L.append("**References:** " + " · ".join(f.references) + "\n")
        if f.tools:
            L.append("**Tools:** " + ", ".join(f.tools) + "\n")
        L.append("---\n")

    if meta.get("notes"):
        L.append("## Run notes\n")
        for n in meta["notes"]:
            L.append(f"- {n}")
        L.append("")
    return "\n".join(L)


# ── HTML report ───────────────────────────────────────────────────────────────

# Severity swatches — kept in sync with the CSS `--crit/--high/...` vars in
# templates/report.html.j2. Used for inline card/distribution/finding accents.
_HTML_SEV_COLOR = {
    "CRITICAL": "#7f1d1d", "HIGH": "#c2410c", "MEDIUM": "#a16207",
    "LOW": "#1d4ed8", "INFO": "#52525b", "SAFE": "#15803d",
}
_SEV_CARDS = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


def _jinja_env():
    """Jinja2 environment rooted at core/templates/.

    autoescape is forced on (not select_autoescape) because the template is named
    ``report.html.j2`` — the ``.j2`` suffix would make extension-based selection skip
    escaping, letting a ``<`` inside a finding break the markup or inject script.
    """
    from jinja2 import Environment, FileSystemLoader
    tpl_dir = os.path.join(os.path.dirname(__file__), "templates")
    return Environment(
        loader=FileSystemLoader(tpl_dir),
        autoescape=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def _render_html(findings: list[Finding], meta: dict) -> str:
    from .chains import build_chains
    from .taxonomy import CVSS_BAND

    real = [f for f in findings if f.severity != "SAFE"]
    counts = {s: sum(1 for f in real if f.severity == s) for s in _SEV_CARDS}
    safe_n = sum(1 for f in findings if f.severity == "SAFE")
    ordered = sorted(findings, key=lambda f: (_SEV_ORDER[f.severity], f.owasp))
    total_real = len(real)

    dist = [{"sev": s, "n": counts[s], "color": _HTML_SEV_COLOR[s],
             "pct": round(100.0 * counts[s] / total_real, 2)}
            for s in _SEV_CARDS if counts[s]] if total_real else []

    chains = [{"severity": c.severity, "title": c.title, "steps": list(c.steps),
               "finding_ids": list(c.finding_ids),
               "color": _HTML_SEV_COLOR.get(c.severity, _HTML_SEV_COLOR["HIGH"])}
              for c in build_chains(findings)]

    fctx = []
    for i, f in enumerate(ordered, 1):
        blocks = [{"lbl": lbl, "val": val.strip()} for lbl, val in (
            ("Triggering request", f.request),
            ("Evidence / PoC", f.evidence),
            ("Reproduction", f.reproduction)) if val]
        fctx.append({
            "i": i, "severity": f.severity, "title": f.title, "owasp": f.owasp,
            "owasp_full": OWASP_2021[f.owasp], "cvss": CVSS_BAND[f.severity],
            "id": f.id, "module": f.module, "route": f.route, "location": f.location,
            "summary": f.summary, "color": _HTML_SEV_COLOR[f.severity],
            "blocks": blocks, "references": f.references, "tools": f.tools,
        })

    ctx = {
        "app": meta.get("app_name", "target"),
        "base_url": meta.get("base_url"), "date": meta.get("date"),
        "framework": meta.get("framework", "FastAPI"),
        "safe": bool(meta.get("safe")),
        "route_count": meta.get("route_count", "?"),
        "principal_count": len(meta.get("principals") or []),
        "sev_order": _SEV_CARDS, "colors": _HTML_SEV_COLOR,
        "counts": counts, "safe_n": safe_n, "total_real": total_real,
        "dist": dist, "chains": chains, "findings": fctx,
        "notes": meta.get("notes") or [],
    }
    return _jinja_env().get_template("report.html.j2").render(**ctx)
